workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      node: latest
      ruby: 3.2.2
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
